# Best 5 functions from Pytorch Library

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab (FAIR) 

- torch.chunk
- torch.reshape
- torch.where()
- ftorch.exp
- torch.sort()


In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.chunk

Splits a tensor into a specific number of chunks.(Slicing)

In [10]:
tensor = torch.arange(0, 10, 2)
print(tensor)
torch.chunk(tensor, 2)

tensor([0, 2, 4, 6, 8])


(tensor([0, 2, 4]), tensor([6, 8]))

Explanation about example Here we see that we first created a tensor with the arange function and the we used the chunk fucntion to that tensor and splitted in two different tensor. Note that the second tensor has only two elements instead of three of the first element.

In [11]:
tensor2 = torch.arange(0, 100, 5)
print(tensor2)
torch.chunk(tensor2, 3, 0)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])


(tensor([ 0,  5, 10, 15, 20, 25, 30]),
 tensor([35, 40, 45, 50, 55, 60, 65]),
 tensor([70, 75, 80, 85, 90, 95]))

Explanation about example Here we created a tensor (tensor2) with the arange function; then we created 3 chunks and please note that the last tensor has one less element than the rest.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
tensor3 = torch.arange(0, 100, 5)
print(tensor3)
torch.chunk(tensor2, 3, -1.0)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])


TypeError: chunk(): argument 'dim' (position 3) must be int, not float

Explanation about example Same case as above, however we used a float value for the dim parameter; only integers are allowed here.


Closing comments about when to use this function Same as before, we can manipulate the data of our tensors and adjust to the relevant case there is at the moment, note that the restrictions for the dim parameter are not very straigth

Let's save our work using Jovian before continuing.

In [13]:
!pip install jovian --upgrade --quiet

In [14]:
import jovian

<IPython.core.display.Javascript object>

In [15]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "i16ph021/01-tensor-operations"
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/i16ph021/01-tensor-operations


'https://jovian.ai/i16ph021/01-tensor-operations'

## Function 2 - torch.reshape 

Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior.

In [19]:
tensor4 = torch.arange(8.)
torch.reshape(tensor4, (2,4))

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

First the tensor was created with the arange method (only 1 dimension).

Then we RESHAPE it with the function and transformed it to a 2 x 4 matrix).

In [20]:
tensor5 = torch.arange(16,)
torch.reshape(tensor5, (4, 4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

Explanation about example
Same case as before, we just reshaped the tensor (tensor5) to a new more usable tensor with desired shape.

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
torch.reshape(tensor5, (3, 3))

RuntimeError: shape '[3, 3]' is invalid for input of size 16


Here we tried the same a before, however the shape designated to our original table does't match our
original elements displayed. 
Closing comments about when to use this function This function is very powerful and it would surely help with handling of better information regarding children at the partk!

Closing comments about when to use this function

In [22]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "i16ph021/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/i16ph021/01-tensor-operations


'https://jovian.ai/i16ph021/01-tensor-operations'

## Function 3 - torch.where()

Function 3 - torch.where()

Return a tensor of elements selected from either x or y, depending on condition.

if x then x otherwise y.


In [23]:
tx = torch.randn(4,2)
ty = torch.zeros_like(tx)
print(tx)
print(ty)
torch.where(tx == ty, tx, ty)

tensor([[-0.3941,  1.2615],
        [ 2.3119,  1.2217],
        [ 0.8097, -1.1456],
        [ 1.2478,  0.5558]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

It returns ty as tx is not equal to ty.

In [24]:
torch.where(tx > 0.3, tx, ty)

tensor([[0.0000, 1.2615],
        [2.3119, 1.2217],
        [0.8097, 0.0000],
        [1.2478, 0.5558]])

Here it returns tx as tx > 0.3 is True

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
torch.where(True, tx, ty)

TypeError: where() received an invalid combination of arguments - got (bool, Tensor, Tensor), but expected one of:
 * (Tensor condition)
 * (Tensor condition, Tensor input, Tensor other)
      didn't match because some of the arguments have invalid types: (!bool!, Tensor, Tensor)
 * (Tensor condition, Number self, Tensor other)
      didn't match because some of the arguments have invalid types: (!bool!, !Tensor!, Tensor)
 * (Tensor condition, Tensor input, Number other)
      didn't match because some of the arguments have invalid types: (!bool!, Tensor, !Tensor!)
 * (Tensor condition, Number self, Number other)
      didn't match because some of the arguments have invalid types: (!bool!, !Tensor!, !Tensor!)


his fails because the condition passed in where() should be Tensor condition otherwise it fails with this error

Closing comments about when to use this function

In [26]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "i16ph021/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/i16ph021/01-tensor-operations


'https://jovian.ai/i16ph021/01-tensor-operations'

## Function 4 - torch.exp

It is a function that returns a new tensor with the exponential of the elements of the input tensor.

In [37]:
# Example 1 - working
new_tensor = torch.tensor(13.)
torch.exp(new_tensor)


tensor(442413.4062)

As said above, the torch.exp function returns a tensor with the exponents of the elements and here we have only passed a single element which is a float64 whose exponential is then returned.

In [38]:
import math
torch.exp(torch.tensor([0, math.log(13.)]))

tensor([ 1.0000, 13.0000])

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
new_tensor1 = torch.tensor(13)
torch.exp(new_tensor1)

RuntimeError: exp_vml_cpu not implemented for 'Long'

Data type should be float64.mainly output of exp funcation is float

Closing comments about when to use this function

In [40]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "i16ph021/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/i16ph021/01-tensor-operations


'https://jovian.ai/i16ph021/01-tensor-operations'

# Function 5 - torch.sort()

The function sorts the elements of the input tensor. Remember, it sorts according to the values and thus index gets jumbled accordingly.

##Default parameters:
It sorts by a dimension in "ascending order by value" and 
If dim is not given, the last dimension of the input is chosen.

##Syntax:
torch.sort(input, dim=-1, descending=False, *, out=None) -> (Tensor, LongTensor)

In [41]:
# Example 1 - working
a= torch.tensor([1,2,13,66,58,44])
torch.sort(a)

torch.return_types.sort(
values=tensor([ 1,  2, 13, 44, 58, 66]),
indices=tensor([0, 1, 2, 5, 4, 3]))

In [42]:
# Example 2 - working
x=torch.tensor([[-0.2162,  0.0608,  0.6719,  2.3332],
        [-0.5793,  0.0061,  0.6058,  0.9497],
        [-0.5071,  0.3343,  0.9553,  1.0960]])
sorted, indices = torch.sort(x)
print(sorted,indices)
sorted, indices = torch.sort(x, 1) #along a dimension
sorted
indices

tensor([[-0.2162,  0.0608,  0.6719,  2.3332],
        [-0.5793,  0.0061,  0.6058,  0.9497],
        [-0.5071,  0.3343,  0.9553,  1.0960]]) tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])


tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])

A namedtuple of (values, indices) is returned, where the values are the sorted values and indices are the indices of the elements in the original input tensor.

these are the two tensor which has been printed when called on sorted and indices.


In [49]:
# Example 3 - breaking (to illustrate when it breaks)
a= torch.tensor([[1,2,-3,-3],[0,6,5,4,5]])
torch.sort(a)

ValueError: expected sequence of length 4 at dim 1 (got 5)

Here the shape of tensor will be 2D in nature, thus anything greater than index"0" won't be accessible for the given tensor.

Closing comments about when to use this function

In [50]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "i16ph021/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/i16ph021/01-tensor-operations


'https://jovian.ai/i16ph021/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
