
# Numpy

Use the "Run" button to execute the code.

### Q1 What is the shape of the following NumPy array?

In [2]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
A.shape

(2, 3)

### Q2 What is the output of the following snippet of code?

In [4]:
import numpy as np

A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])
print(A[1, 2: 4])

[8 9]


### Q3 What does B correspond to? The first row is [1, 2, 3, 4] and the first column is $[1, 5, 9, 13]^T$ 

In [4]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

B = A[:, 2]

In [5]:
B

array([ 3,  7, 11, 15])

### Q4 What is the output of the following snippet of code?

In [7]:
import numpy as np

A = np.array([[1, 1, 2, 3], 
              [4, 5, 1, 4], 
              [1, 9, 10, 11]])

print(A.sum(axis = 0))

[ 6 15 13 18]


### Q5 What is the output of the following snippet of code?

In [8]:
A = np.array(([1, 2, 3]))
B = np.array([[4, 5, 6]])
print(A + B)

[[5 7 9]]


### Q6 Consider the vectors $$
\mathbf{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
$$

$$
\mathbf{y}  = \begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$
Which of the following commands prints the dot product of the two vectors? 

In [9]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x @ y)

32


In [10]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x * y)

[ 4 10 18]


In [11]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.dot(x, y))

32


In [12]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.sum(x * y))

32


### Q7 What is the output of the following snippet of code?

In [13]:
import numpy as np

w = np.zeros(5)
w = w + 2
print(w)

[2. 2. 2. 2. 2.]


### Q8 `np.linspace(a, b, n)` is a method that returns an array of nn evenly spaced points between [a, b]. For example, `np.linspace(0, 1, 5)` is the array [0., 0.25, 0.5, 0.75, 1.]. With this information, what is the output of the following snippet of code?

In [14]:
import numpy as np

x = np.linspace(-1, 1, 5)
y = 2 * x + 4
print(y)

[2. 3. 4. 5. 6.]


In [15]:
A = np.array([[1, 2], [1, 3], [1, 5]])
x = np.array([1, 2])
b = np.array([3, 4, 5])

A * x - b


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [16]:
A = np.array([[1, 2], [1, 3], [1, 5]])
x = np.array([1, 2])
b = np.array([3, 4, 5])

A @ x - b

array([2, 3, 6])

In [17]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3, 4])
b = np.expand_dims(b, axis = 1)
M + b

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [18]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3])
b = np.expand_dims(b, axis = 1)
M + b

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [19]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3])
M + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 